// Auswählbare Benutzer-Avatare (stilisierte Icons statt echter Schauspielerfotos).
const AVATARS = {
  ahmet: {
    name: "Ahmet",
    hero: "Steve Rogers / Captain America",
    color: "#3b5bdb",
    svg: `<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
      <circle cx="50" cy="50" r="48" fill="#a5121b"/>
      <circle cx="50" cy="50" r="37" fill="#eef0f4"/>
      <circle cx="50" cy="50" r="26" fill="#1b3d8f"/>
      <circle cx="50" cy="50" r="12" fill="#eef0f4"/>
      <polygon points="50,36 54,46 65,46 56,53 59,64 50,57 41,64 44,53 35,46 46,46" fill="#1b3d8f"/>
    </svg>`,
  },
  burak: {
    name: "Burak",
    hero: "Tony Stark / Iron Man",
    color: "#c9962f",
    svg: `<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
      <path d="M50 4C74 4 86 22 86 46 86 70 74 92 50 98 26 92 14 70 14 46 14 22 26 4 50 4Z" fill="#7a0f14"/>
      <path d="M50 10C70 10 78 26 78 46 78 66 68 86 50 92 32 86 22 66 22 46 22 26 30 10 50 10Z" fill="#c9962f"/>
      <path d="M50 16C66 16 72 30 72 46 72 62 64 80 50 86 36 80 28 62 28 46 28 30 34 16 50 16Z" fill="#a5121b"/>
      <path d="M34 42 46 40 46 48 36 50Z" fill="#eaffff"/>
      <path d="M66 42 54 40 54 48 64 50Z" fill="#eaffff"/>
      <rect x="46" y="55" width="8" height="24" rx="3" fill="#c9962f"/>
      <path d="M38 76Q50 87 62 76L62 82Q50 91 38 82Z" fill="#c9962f"/>
    </svg>`,
  },
};

// Alle MCU-Filme in chronologischer Erscheinungsreihenfolge, bis Avengers: Doomsday.
const MCU_TIMELINE = [
  {
    phase: "Phase 1",
    films: [
      { title: "Iron Man", year: 2008 },
      { title: "Der unglaubliche Hulk", year: 2008 },
      { title: "Iron Man 2", year: 2010 },
      { title: "Thor", year: 2011 },
      { title: "Captain America: The First Avenger", year: 2011 },
      { title: "The Avengers", year: 2012 },
    ],
  },
  {
    phase: "Phase 2",
    films: [
      { title: "Iron Man 3", year: 2013 },
      { title: "Thor: The Dark World", year: 2013 },
      { title: "Captain America: The Return of the First Avenger", year: 2014 },
      { title: "Guardians of the Galaxy", year: 2014 },
      { title: "Avengers: Age of Ultron", year: 2015 },
      { title: "Ant-Man", year: 2015 },
    ],
  },
  {
    phase: "Phase 3",
    films: [
      { title: "Captain America: Civil War", year: 2016 },
      { title: "Doctor Strange", year: 2016 },
      { title: "Guardians of the Galaxy Vol. 2", year: 2017 },
      { title: "Spider-Man: Homecoming", year: 2017 },
      { title: "Thor: Ragnarok", year: 2017 },
      { title: "Black Panther", year: 2018 },
      { title: "Avengers: Infinity War", year: 2018 },
      { title: "Ant-Man and the Wasp", year: 2018 },
      { title: "Captain Marvel", year: 2019 },
      { title: "Avengers: Endgame", year: 2019 },
      { title: "Spider-Man: Far From Home", year: 2019 },
    ],
  },
  {
    phase: "Phase 4",
    films: [
      { title: "Black Widow", year: 2021 },
      { title: "Shang-Chi and the Legend of the Ten Rings", year: 2021 },
      { title: "Eternals", year: 2021 },
      { title: "Spider-Man: No Way Home", year: 2021 },
      { title: "Doctor Strange in the Multiverse of Madness", year: 2022 },
      { title: "Thor: Love and Thunder", year: 2022 },
      { title: "Black Panther: Wakanda Forever", year: 2022 },
    ],
  },
  {
    phase: "Phase 5",
    films: [
      { title: "Ant-Man and the Wasp: Quantumania", year: 2023 },
      { title: "Guardians of the Galaxy Vol. 3", year: 2023 },
      { title: "The Marvels", year: 2023 },
      { title: "Deadpool & Wolverine", year: 2024 },
    ],
  },
  {
    phase: "Phase 6",
    films: [
      { title: "Captain America: Brave New World", year: 2025 },
      { title: "Thunderbolts*", year: 2025 },
      { title: "The Fantastic Four: First Steps", year: 2025 },
      { title: "Avengers: Doomsday", year: 2026, finale: true },
    ],
  },
];

// Datengrundlage für alle Marvel-Universen, die als Planeten dargestellt werden.
const UNIVERSES = [
  {
    id: "tobey",
    name: "Sam Raimi Spider-Man",
    eyebrow: "Universum · Tobey Maguire",
    colorA: "#8b0f0f",
    colorB: "#173d8f",
    accent: "#ff4d4d",
    radius: 2.1,
    orbitRadius: 15,
    orbitSpeed: 0.055,
    startAngle: 0.2,
    yOffset: 0.5,
    desc: "Das Universum, das den modernen Superheldenfilm neu erfunden hat. Peter Parker balanciert zwischen Verantwortung und Verlust in New York City.",
    characters: [
      { name: "Peter Parker / Spider-Man", role: "Tobey Maguire" },
      { name: "Mary Jane Watson", role: "Kirsten Dunst" },
      { name: "Harry Osborn / New Goblin", role: "James Franco" },
      { name: "Norman Osborn / Green Goblin", role: "Willem Dafoe" },
      { name: "Otto Octavius / Doc Ock", role: "Alfred Molina" },
      { name: "Eddie Brock / Venom", role: "Topher Grace" },
      { name: "Flint Marko / Sandman", role: "Thomas Haden Church" },
      { name: "Tante May", role: "Rosemary Harris" },
    ],
    movies: [
      { title: "Spider-Man", year: 2002 },
      { title: "Spider-Man 2", year: 2004 },
      { title: "Spider-Man 3", year: 2007 },
      { title: "Spider-Man: No Way Home (Cameo)", year: 2021 },
    ],
  },
  {
    id: "garfield",
    name: "The Amazing Spider-Man",
    eyebrow: "Universum · Andrew Garfield",
    colorA: "#a3121f",
    colorB: "#0e7c86",
    accent: "#38d4e0",
    radius: 1.9,
    orbitRadius: 21,
    orbitSpeed: 0.045,
    startAngle: 2.4,
    yOffset: -1.2,
    desc: "Ein grüblerischerer, wissenschaftlich getriebener Peter Parker erkundet das Verschwinden seiner Eltern und verliebt sich in Gwen Stacy — mit tragischen Folgen.",
    characters: [
      { name: "Peter Parker / Spider-Man", role: "Andrew Garfield" },
      { name: "Gwen Stacy", role: "Emma Stone" },
      { name: "Harry Osborn", role: "Dane DeHaan" },
      { name: "Curt Connors / The Lizard", role: "Rhys Ifans" },
      { name: "Max Dillon / Electro", role: "Jamie Foxx" },
      { name: "Aleksei Sytsevich / Rhino", role: "Paul Giamatti" },
      { name: "Captain George Stacy", role: "Denis Leary" },
      { name: "Tante May", role: "Sally Field" },
    ],
    movies: [
      { title: "The Amazing Spider-Man", year: 2012 },
      { title: "The Amazing Spider-Man 2", year: 2014 },
      { title: "Spider-Man: No Way Home (Cameo)", year: 2021 },
    ],
  },
  {
    id: "holland",
    name: "MCU Spider-Man",
    eyebrow: "Universum · Tom Holland",
    colorA: "#b3231d",
    colorB: "#c9a227",
    accent: "#ffce54",
    radius: 2.3,
    orbitRadius: 27,
    orbitSpeed: 0.038,
    startAngle: 4.1,
    yOffset: 1.0,
    desc: "Ein junger, technikbegeisterter Peter Parker wächst im Schatten von Iron Man auf und wird Teil des Marvel Cinematic Universe — bis die Multiversum-Grenzen einreißen.",
    characters: [
      { name: "Peter Parker / Spider-Man", role: "Tom Holland" },
      { name: "MJ (Michelle Jones)", role: "Zendaya" },
      { name: "Ned Leeds", role: "Jacob Batalon" },
      { name: "Tony Stark / Iron Man", role: "Robert Downey Jr." },
      { name: "Happy Hogan", role: "Jon Favreau" },
      { name: "Tante May", role: "Marisa Tomei" },
      { name: "Quentin Beck / Mysterio", role: "Jake Gyllenhaal" },
      { name: "Adrian Toomes / Vulture", role: "Michael Keaton" },
      { name: "Doctor Strange", role: "Benedict Cumberbatch" },
    ],
    movies: [
      { title: "Captain America: Civil War", year: 2016 },
      { title: "Spider-Man: Homecoming", year: 2017 },
      { title: "Avengers: Infinity War", year: 2018 },
      { title: "Avengers: Endgame", year: 2019 },
      { title: "Spider-Man: Far From Home", year: 2019 },
      { title: "Spider-Man: No Way Home", year: 2021 },
    ],
  },
  {
    id: "fantasticfour",
    name: "Fantastic Four",
    eyebrow: "Universum · Erste Familie Marvels",
    colorA: "#1b3a8a",
    colorB: "#c7d2dd",
    accent: "#7fb3ff",
    radius: 2.4,
    orbitRadius: 33,
    orbitSpeed: 0.03,
    startAngle: 1.1,
    yOffset: -0.6,
    desc: "Vier Astronauten werden durch kosmische Strahlung verändert und müssen als Familie zusammenhalten — gegen Bedrohungen, die ganze Realitäten umformen können.",
    characters: [
      { name: "Reed Richards / Mister Fantastic", role: "Pedro Pascal" },
      { name: "Sue Storm / Invisible Woman", role: "Vanessa Kirby" },
      { name: "Johnny Storm / Human Torch", role: "Joseph Quinn" },
      { name: "Ben Grimm / The Thing", role: "Ebon Moss-Bachrach" },
      { name: "Victor von Doom / Doctor Doom", role: "Robert Downey Jr." },
      { name: "Silver Surfer", role: "Julia Garner" },
    ],
    movies: [
      { title: "Fantastic Four", year: 2005 },
      { title: "Fantastic Four: Rise of the Silver Surfer", year: 2007 },
      { title: "Fantastic Four", year: 2015 },
      { title: "The Fantastic Four: First Steps", year: 2025 },
    ],
  },
  {
    id: "thunderbolts",
    name: "Thunderbolts",
    eyebrow: "Universum · Die neuen Avengers",
    colorA: "#3b1e5c",
    colorB: "#1c2230",
    accent: "#b48cff",
    radius: 1.8,
    orbitRadius: 39,
    orbitSpeed: 0.026,
    startAngle: 5.3,
    yOffset: 1.4,
    desc: "Eine Gruppe von Antihelden, Attentätern und gebrochenen Agenten wird zwangsweise zu einem Team — und findet sich als neue Avengers wieder.",
    characters: [
      { name: "Yelena Belova", role: "Florence Pugh" },
      { name: "Bucky Barnes / Winter Soldier", role: "Sebastian Stan" },
      { name: "Alexei Shostakov / Red Guardian", role: "David Harbour" },
      { name: "Ava Starr / Ghost", role: "Hannah John-Kamen" },
      { name: "John Walker / U.S. Agent", role: "Wyatt Russell" },
      { name: "Antonia Dreykov / Taskmaster", role: "Olga Kurylenko" },
      { name: "Valentina Allegra de Fontaine", role: "Julia Louis-Dreyfus" },
      { name: "Bob Reynolds / Sentry & The Void", role: "Lewis Pullman" },
    ],
    movies: [
      { title: "Black Widow (Ursprung)", year: 2021 },
      { title: "Thunderbolts*", year: 2025 },
    ],
  },
  {
    id: "xmen",
    name: "X-Men",
    eyebrow: "Universum · Mutanten",
    colorA: "#132a63",
    colorB: "#d4af37",
    accent: "#ffd75e",
    radius: 2.5,
    orbitRadius: 45,
    orbitSpeed: 0.022,
    startAngle: 3.3,
    yOffset: -1.5,
    desc: "Mutanten mit außergewöhnlichen Kräften kämpfen für ein friedliches Miteinander mit der Menschheit — angeführt von den gegensätzlichen Visionen von Xavier und Magneto.",
    characters: [
      { name: "Charles Xavier / Professor X", role: "Patrick Stewart" },
      { name: "Erik Lehnsherr / Magneto", role: "Ian McKellen" },
      { name: "Logan / Wolverine", role: "Hugh Jackman" },
      { name: "Raven / Mystique", role: "Rebecca Romijn" },
      { name: "Ororo Munroe / Storm", role: "Halle Berry" },
      { name: "Scott Summers / Cyclops", role: "James Marsden" },
      { name: "Jean Grey / Phoenix", role: "Famke Janssen" },
      { name: "Hank McCoy / Beast", role: "Nicholas Hoult" },
      { name: "Wade Wilson / Deadpool", role: "Ryan Reynolds" },
    ],
    movies: [
      { title: "X-Men", year: 2000 },
      { title: "X2", year: 2003 },
      { title: "X-Men: The Last Stand", year: 2006 },
      { title: "X-Men Origins: Wolverine", year: 2009 },
      { title: "X-Men: First Class", year: 2011 },
      { title: "The Wolverine", year: 2013 },
      { title: "X-Men: Days of Future Past", year: 2014 },
      { title: "Deadpool", year: 2016 },
      { title: "X-Men: Apocalypse", year: 2016 },
      { title: "Logan", year: 2017 },
      { title: "Deadpool 2", year: 2018 },
      { title: "Dark Phoenix", year: 2019 },
      { title: "The New Mutants", year: 2020 },
    ],
  },
  {
    id: "doomsday",
    name: "Avengers: Doomsday",
    eyebrow: "Universum · Multiversum-Konvergenz",
    colorA: "#0d3320",
    colorB: "#7a4a12",
    accent: "#ff5a3c",
    radius: 3.1,
    orbitRadius: 12,
    orbitSpeed: 0,
    startAngle: -0.6,
    yOffset: 2.6,
    isDoomsday: true,
    releaseDate: "2026-12-18T00:00:00",
    desc: "Doctor Doom bricht in das Kernuniversum ein — und reißt die Grenzen zwischen den Welten der Avengers, X-Men und Fantastic Four endgültig ein. Der bislang größte Marvel-Crossover.",
    characters: [
      { name: "Victor von Doom / Doctor Doom", role: "Robert Downey Jr." },
      { name: "Sam Wilson / Captain America", role: "Anthony Mackie" },
      { name: "Charles Xavier / Professor X", role: "Patrick Stewart" },
      { name: "Erik Lehnsherr / Magneto", role: "Ian McKellen" },
      { name: "Ororo Munroe / Storm", role: "Halle Berry" },
      { name: "Reed Richards / Mister Fantastic", role: "Pedro Pascal" },
      { name: "Sue Storm / Invisible Woman", role: "Vanessa Kirby" },
      { name: "Bucky Barnes / Winter Soldier", role: "Sebastian Stan" },
      { name: "Yelena Belova", role: "Florence Pugh" },
    ],
    movies: [
      { title: "Avengers: Doomsday", year: 2026 },
    ],
  },
];
